# Generated by Django 2.2.12 on 2020-05-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='model_pic',
            field=models.ImageField(default='challenges/images/already.jpg', upload_to='upload_image'),
        ),
    ]
